### ISSUE TITLE
README rewrite

### ISSUE THREAD

**Issue by taraokelly** [taraokelly/Gesture-Based-Assignment#5]
Adapt README to suit headings provided in [spec.pdf](https://github.com/taraokelly/Gesture-Based-Assignment/blob/master/spec.pdf).

**Comment by rebeccabkane** [comment]
Headings added in to README with detailed descriptions. Also added game implementation logic to README, described by @taraokelly in the [Notes](https://github.com/taraokelly/Gesture-Based-Assignment/blob/master/Notes.md) file.  
Closing issue.
